[phases.setup]
nixPkgs = ['nodejs_20', 'python3', 'python3-dev', 'gcc', 'g++', 'make']
nixpkgsArchive = 'ba913eda2df8eb72147259189d55932012df6301'

[phases.install]
cmds = [
  'cd server',
  'npm install --verbose'
]

[phases.build]
cmds = [
  'cd server',
  'npm run build'
]

[start]
cmd = 'cd server && npm start'