[phases.setup]
nixPkgs = ['nodejs_18', 'python3']

[phases.install]
cmds = [
  'cd server',
  'npm install'
]

[phases.build]
cmds = [
  'cd server', 
  'npm run build'
]

[start]
cmd = 'cd server && npm start'
